name = "beenycool-ai-gcse-marker"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]

# For Next.js applications, use pages configuration instead of workers
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages"

# Environment variables
[env.production.vars]
NODE_ENV = "production"