name = "beenycool-ai-gcse-marker"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]

# For Next.js applications, use pages configuration
pages_build_output_dir = ".next"

# Environment variables
[env.production.vars]
NODE_ENV = "production"