name: Keep Backend Awake

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend to keep it awake
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://beenycool-github-io.onrender.com || true 