name: Test Deployment

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Test secret configuration
      run: |
        echo "Testing Cloudflare secrets..."
        if [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
          echo "✅ CLOUDFLARE_API_TOKEN is configured"
        else
          echo "❌ CLOUDFLARE_API_TOKEN is missing"
        fi
        
        if [ -n "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
          echo "✅ CLOUDFLARE_ACCOUNT_ID is configured"
        else
          echo "❌ CLOUDFLARE_ACCOUNT_ID is missing"
        fi

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test-secrets
    permissions:
      contents: read
      deployments: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: |
        npx rimraf .next out
        npx next build

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: beenycool-github-io
        directory: out
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        wranglerVersion: '3'

    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🌐 Your site should be available at:"
        echo "  - https://beenycool-github-io.pages.dev"
        echo "  - Your custom domain (if configured)"